version: 2.1

jobs:
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print World"
          command: "echo World "
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print Hello"
          command: "echo Hello!"
  print_env_variable:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print Variable"
          command: "echo $MY_NAME"

workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_env_variable
